name: LunaSpring
version: '${project.version}'
main: org.novasparkle.lunaspring.LunaSpring
api-version: '1.16'
commands:
  lunaspring:
    aliases:
      - lsp
      - ls
      - spring
      - lspring
  plugins:
    aliases:
      - pl
  lunaevent:
    aliases:
      - e
      - ev
      - event
      - lunae
      - levent
      - le
      - lev
authors:
  - NovaSparkle
  - ProGiple

softdepend:
  - NBTAPI
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI

permissions:
  lunaspring.*:
    default: false
  lunaspring.reload:
    default: op
  lunaspring.server-info:
    default: op
  lunaspring.hooked:
    default: op
  lunaspring.plugins:
    default: op
  lunaspring.event.delay:
    default: op
  lunaspring.event.teleport:
    default: op
  lunaspring.event.compass:
    default: op
  lunaspring.event.locate:
    default: op
  lunaspring.event.start:
    default: op
  lunaspring.event.stop:
    default: op