name: LunaSpring
version: '${project.version}'
main: org.novasparkle.lunaspring.LunaSpring
api-version: '1.16'
commands:
  lunaspring:
    aliases:
      - lsp
      - ls
authors:
  - NovaSparkle
  - ProGiple

softdepend:
  - NBTAPI
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI

permissions:
  lunaspring.reload:
    default: op
  lunaspring.server-info:
    default: op
  lunaspring.hooked:
    default: op